# shared values
server_port: "8443"
protocol: "https"


# values for agent
server_ip: "192.168.2.11"
timing:
  delay: "5s"
  jitter: 50

# values for server
listening_interface: "0.0.0.0"
tls_key: "./certs/server.key"
tls_cert: "./certs/server.crt"