# shared values
server_port: "8443"
protocol: "dns"


# values for agent
server_ip: "127.0.0.1"
timing:
  delay: "5s"
  jitter: 50

# values for server
listening_interface: "127.0.0.1"
tls_key: "./certs/server.key"
tls_cert: "./certs/server.crt"